# Ch 19,20 : 데이터프레임의 요약정보 확인하기

### Pandas 활용하기

- Pandas를 import 합니다
- csv파일 하나를 동일 디렉토리로 가져옵니다
- csv파일을 읽어서 DataFrame으로 읽어옵니다

In [3]:
import pandas as pd
import os

In [6]:
csv_list = list(filter(lambda x:x.endswith('csv'),os.listdir()))

In [10]:
df = pd.read_csv(csv_list[0])

In [11]:
df

         시점     지표  전기대비증감률
0   2014.00   84.8      1.8
1   2015.00   87.7      3.4
2   2016.00   88.4      0.8
3   2017.00   89.7      1.5
4   2018.00   90.6      1.0
5   2019.00   90.3     -0.3
6   2020.00   95.2      5.4
7   2020.11   94.3      0.5
8   2020.12   95.2      1.0
9   2021.10   95.9      0.7
10  2021.20   96.8      0.9
11  2021.30   97.5      0.7
12  2021.40   98.2      0.7
13  2021.50   98.9      0.7
14  2021.60  100.0      1.1
15  2021.70  100.9      0.9
16  2021.80  101.8      0.9
17  2021.90  102.8      1.0
18  2021.10  103.7      0.9
19  2021.11  104.3      0.6

### DataFrame head(), tail() 생각하기

- 앞에서 배운 head(),tail()을 사용해서 각각 7개의 행씩 읽어와 봅니다

In [12]:
df.head(7)

       시점    지표  전기대비증감률
0  2014.0  84.8      1.8
1  2015.0  87.7      3.4
2  2016.0  88.4      0.8
3  2017.0  89.7      1.5
4  2018.0  90.6      1.0
5  2019.0  90.3     -0.3
6  2020.0  95.2      5.4

In [13]:
df.tail(7)

         시점     지표  전기대비증감률
13  2021.50   98.9      0.7
14  2021.60  100.0      1.1
15  2021.70  100.9      0.9
16  2021.80  101.8      0.9
17  2021.90  102.8      1.0
18  2021.10  103.7      0.9
19  2021.11  104.3      0.6

### info()메소드 활용하기

info()메소드를 사용하면, 데이터 프레임의 자료형과 행 인덱스의 종류와 개수, 열의 개수와 자료형, 메모리 총 사용량 등 **데이터프레임의 기본정보**를 확인할 수 있습니다.

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   시점       20 non-null     float64
 1   지표       20 non-null     float64
 2   전기대비증감률  20 non-null     float64
dtypes: float64(3)
memory usage: 608.0 bytes

### describe()메소드 활용하기

describe()메소드를 사용하면, **데이터 프레임의 통계정보**를 출력할 수 있습니다. 결과물의 각 필드가 의미하는것은 아래와 같습니다

- count : 각 열의 데이터 개수
- mean : 평균값
- std : 표준편차
- min,max : 최소,최댓값
- 사분위값

In [15]:
df.describe()

                시점          지표    전기대비증감률
count    20.000000   20.000000  20.000000
mean   2019.747000   95.850000   1.210000
std       2.439137    5.718714   1.206954
min    2014.000000   84.800000  -0.300000
25%    2018.750000   90.525000   0.700000
50%    2021.100000   96.350000   0.900000
75%    2021.425000  100.225000   1.025000
max    2021.900000  104.300000   5.400000